* Web Administration Tool
A tool for managing the contents of your website. The following project makes it possible for you to
manage a blog, a project section or any other form of content. 

** Dependencies
The project was made using:
- Java 11
- Maven
- Spring Framework
- JUnit
- Apache derby
- Jasper

* Demo
In order to demo the project just run the main file "WebAdminToolApp" and then use the following
login information:

- user
- password

No emphasis was put on the security of the login authentication as it was outside the 
scope of the project. So please make sure you harden the spring security when using this project
for your own use. 

The demo runs on a local database setup by apache derby, so nothing is stored permanently in your
demo run. After login the website should be fairly straight forward to use and interact with. 

** Final words
After having to manually manage my own websites content I ended up doing what a developer does best,
being lazy, so I created this webapp. This particular version is intended for demo purposes, which is 
why the frontend is using a bootstrap 4 template with minor modifications.  

Please feel free to provide constructive feedback!
